#!/bin/bash

cur_branch=echo "$(git branch | awk '/\*/ { print $2; }')"

git checkout master

git remote update --prune

git pull origin master


if [ "$?" != 0 ]; then
  git checkout $cur_branch
  printf "> fail"
  die 1
fi

git checkout $cur_branch && git rebase master $cur_branch

printf "> Master synced with origin"